import type { Metadata } from "next";
import "./globals.css";
import SideNav from "./_components/home/organisms/NavMenu";

export const metadata: Metadata = {
  title: "Athens",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="lg:flex scrollbar-hide justify-center items-start">
        <SideNav />
        {children}
      </body>
    </html>
  );
}
