import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Athens",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="lg:flex scrollbar-hide justify-center items-start w-full">
        {children}
      </body>
    </html>
  );
}
