import type { Metadata } from "next";
import "./globals.css";
import SideNav from "./_components/home/SideNav";
import AgoraUserList from "./_components/AgoraUserList";

export const metadata: Metadata = {
  title: "Athens",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="flex justify-center items-stretch">{children}</div>
      </body>
    </html>
  );
}
